# Generated by Django 3.2.9 on 2021-12-27 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='account.account', verbose_name='user')),
                ('department', models.CharField(blank=True, max_length=15, null=True)),
                ('batch', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(blank=True, max_length=30, null=True)),
                ('reg_num', models.IntegerField(blank=True, null=True)),
                ('mobile_num', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
